### ISSUE TITLE
File-related questions.

### ISSUE THREAD

**Issue by DeepHM** [yyliu01/PS-MT#16]
Hello.
I'm doing some experiments.

Could you share the model file that was trained with Resnet50 or 101 in PASCAL VOC2012?
(If possible, I really want your model file trained with Resnet50 and Resnet101. )

**Comment by yyliu01** [comment]
Thanks for your interest.

I apologize that I've deleted almost all the checkpoints just a few months earlier, because they take so many memories in the google cloud of our namespace. At the moment, I can only support some resnet50 ckpts (in *.zip file) that are based on high-quality 1464 labels (with the training log) and one resnet101 ckpt.

They are in the link below:
https://drive.google.com/drive/folders/1E8JDi3hlUUPpgC-E6SbGHQkTrhrgu3mf?usp=share_link

Hope that could help.

Cheers,
Yuyuan

**Comment by DeepHM** [comment]
Thanks for your kind reply.
