### ISSUE TITLE
Does the prediction from the "running_inference" function rely solely on a single teacher model for estimation?

### ISSUE THREAD

**Issue by Howard-Hsiao** [yyliu01/PS-MT#29]
Hello, 
I noticed some discrepancies between the code used for inference and the formula described in the research paper. I want to comfirm which one is recommended. 

The "running_inference" function utilizes only encoder1 and decoder1 to generate predictions. This means that the function relies solely on teacher 1 for the prediction process.
```{python}
with torch.no_grad():
    prediction = model.module.decoder1(model.module.encoder1(data),
                                       data_shape=[data.shape[-2], data.shape[-1]],
                                       req_feature=True)

conf_result = torch.softmax(prediction.squeeze(), dim=0).max(0)[0]
hard_result = torch.argmax(prediction.squeeze().squeeze(), dim=0)
false_mask = hard_result != target.squeeze()
```

Meanwhile, the inference formula described in the paper involve both teacher 1 and teacher 2. 
![image](https://user-images.githubusercontent.com/35296917/226676534-402f0f57-374f-4c1a-bd4d-e8a5a86fce58.png)

**Comment by yyliu01** [comment]
Hi,

We only utilise single-teacher inference in sliding evaluation of Cityscape dataset to speed up the inference, because some reviewers questioned it in my rebuttal stage. Please feel free to use the ensemble result (i.e., the code in VOC), which brings slightly better performances for most of the split protocol in my experience.

Cheers,
Yuyuan

**Comment by Howard-Hsiao** [comment]
Thank you for your prompt response. I'll proceed to experiment with the ensemble approach.
