### ISSUE TITLE
Question on the implementation of feature perturbation

### ISSUE THREAD

**Issue by Gavinwxy** [yyliu01/PS-MT#32]
Hi, 

Thanks for sharing the code. I am trying to figure out the design of feature perturbation. One questions is that, in [this line of code](https://github.com/yyliu01/PS-MT/blob/61d566e5670b900087a85f1e6021584c168122a9/VocCode/Model/Deeplabv3_plus/encoder_decoder.py#LL69C29-L69C36), what is the purpose of subtracting 0.5 from the random vector? Is it simply an engineering trick or related to some theoretical considerations?

**Comment by yyliu01** [comment]
Hi @Gavinwxy 

Sorry for the late reply, I was in a rush to prepare a rebuttal, and I hope you are still interested in this topic.

In short, rather than calculating a random vector, we infer the VAT perturbation noise, as demonstrated in the [code](https://github.com/yyliu01/PS-MT/blob/61d566e5670b900087a85f1e6021584c168122a9/VocCode/Model/Deeplabv3_plus/encoder_decoder.py#L75) below.
```bash
pred_hat = (decoder1(x_detached + xi * d) + decoder2(x_detached + xi * d))/2
```

The perturbation is based on virtual adversarial training. 
![image](https://github.com/yyliu01/PS-MT/assets/102338056/172147ef-8232-42a0-8b1c-89f82742c66c)
The motivation is to maximize the distance between the perturbed prediction and its original version. Given that the network will remain fixed, the gradient-guided noise is calculated to maximize the distance, and such VAT noise is intended to confuse the network as much as possible. To archive the satisfied perturb effect, the pseudo label's quality is important as it determines the gradient direction.

In our work, we've found the teachers/students are in same domain (please feel free to mean-average the **parameters** of both teachers/students and check the results) and the ensemble of the prediction provides more reliable pseudo-labels during the training process. Hence, we employ teacher ensemble to calculate the VAT perturbation in this [line](https://github.com/yyliu01/PS-MT/blob/61d566e5670b900087a85f1e6021584c168122a9/VocCode/Model/Deeplabv3_plus/encoder_decoder.py#L75) .

Cheers,
Yuyuan

**Comment by Gavinwxy** [comment]
Thanks for your reply. I will check the original VAT paper for more details.

**Comment by yyliu01** [comment]
You are very welcome.
